/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jfx_prop1;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello from jfx_prop1 aplication.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
    
        FXMLLoader loader = new FXMLLoader(this.getClass().getResource("../fxml/app.fxml"));
        Pane pane = null;
        try {
            pane = loader.load();
        } catch (Exception e) {
            e.printStackTrace();
        }

        Scene scene = new Scene(pane);

        primaryStage.setScene(scene);
        primaryStage.setTitle("jfx properties");
        primaryStage.show();
    
    }
}
